providers:
  hetzner:
    regions:
      nbg1:
        name: Nuremberg
      fsn1:
        name: Falkenstein
      hel1:
        name: Helsinki
      ash:
        name: Ashburn, VA
      hil:
        name: Hillsboro, OR
    instances:
    - id: cx23
      name: CX23
      arch: Intel
      vcpu: 2
      ram_gb: 4
      disk_gb: 40
      pricing:
        hourly_eur: 0.00576
        monthly_eur: 3.588
    - id: cax11
      name: CAX11
      arch: ARM64
      vcpu: 2
      ram_gb: 4
      disk_gb: 40
      pricing:
        hourly_eur: 0.00636
        monthly_eur: 3.948
    - id: cpx22
      name: CPX22
      arch: AMD EPYC
      vcpu: 2
      ram_gb: 4
      disk_gb: 80
      pricing:
        hourly_eur: 0.01152
        monthly_eur: 7.188
    - id: cx32
      name: CX32
      arch: Intel
      vcpu: 4
      ram_gb: 8
      disk_gb: 80
      pricing:
        hourly_eur: 0.01152
        monthly_eur: 7.188
    - id: cax21
      name: CAX21
      arch: ARM64
      vcpu: 4
      ram_gb: 8
      disk_gb: 80
      pricing:
        hourly_eur: 0.01152
        monthly_eur: 7.188
    - id: cpx32
      name: CPX32
      arch: AMD EPYC
      vcpu: 4
      ram_gb: 8
      disk_gb: 160
      pricing:
        hourly_eur: 0.02016
        monthly_eur: 12.588
_metadata:
  last_pricing_update: '2026-02-23T16:04:30.634560'
  source: Hetzner Cloud API
