providers:
  hetzner:
    currency: EUR
    default_region: fsn1
    regions:
      nbg1:
        name: Nuremberg
      fsn1:
        name: Falkenstein
      hel1:
        name: Helsinki
      ash:
        name: Ashburn, VA
      hil:
        name: Hillsboro, OR
    instances:
    - id: cx23
      name: CX23
      arch: X86
      vcpu: 2
      ram_gb: 4
      disk_gb: 40
      pricing:
        hourly: 0.00576
        monthly: 3.588
    - id: cx33
      name: CX33
      arch: X86
      vcpu: 4
      ram_gb: 8
      disk_gb: 80
      pricing:
        hourly: 0.0096
        monthly: 5.988
    - id: cax11
      name: CAX11
      arch: ARM64
      vcpu: 2
      ram_gb: 4
      disk_gb: 40
      pricing:
        hourly: 0.00636
        monthly: 3.948
    - id: cax21
      name: CAX21
      arch: ARM64
      vcpu: 4
      ram_gb: 8
      disk_gb: 80
      pricing:
        hourly: 0.01152
        monthly: 7.188
    - id: cpx22
      name: CPX22
      arch: X86
      vcpu: 2
      ram_gb: 4
      disk_gb: 80
      pricing:
        hourly: 0.01152
        monthly: 7.188
    - id: cpx32
      name: CPX32
      arch: X86
      vcpu: 4
      ram_gb: 8
      disk_gb: 160
      pricing:
        hourly: 0.02016
        monthly: 12.588
    - id: ccx13
      name: CCX13
      arch: X86
      vcpu: 2
      ram_gb: 8
      disk_gb: 80
      pricing:
        hourly: 0.02508
        monthly: 15.588
    - id: ccx23
      name: CCX23
      arch: X86
      vcpu: 4
      ram_gb: 16
      disk_gb: 160
      pricing:
        hourly: 0.05004
        monthly: 31.188
  aws:
    currency: USD
    default_region: eu-central-1
    regions:
      eu-central-1:
        name: Frankfurt
    instances:
    - id: t3.micro
      name: t3.micro
      arch: X86
      vcpu: 2
      ram_gb: 1
      disk_gb: 20
      pricing:
        hourly: 0.012
        monthly: 8.64
    - id: t3.small
      name: t3.small
      arch: X86
      vcpu: 2
      ram_gb: 2
      disk_gb: 20
      pricing:
        hourly: 0.024
        monthly: 17.28
    - id: t4g.micro
      name: t4g.micro
      arch: ARM64
      vcpu: 2
      ram_gb: 1
      disk_gb: 20
      pricing:
        hourly: 0.0096
        monthly: 6.91
    - id: t4g.small
      name: t4g.small
      arch: ARM64
      vcpu: 2
      ram_gb: 2
      disk_gb: 20
      pricing:
        hourly: 0.0192
        monthly: 13.82
    - id: c7i-flex.large
      name: c7i-flex.large
      arch: X86
      vcpu: 2
      ram_gb: 4
      disk_gb: 20
      pricing:
        hourly: 0.09676
        monthly: 69.67
    - id: m7i-flex.large
      name: m7i-flex.large
      arch: X86
      vcpu: 2
      ram_gb: 8
      disk_gb: 20
      pricing:
        hourly: 0.11471
        monthly: 82.59
exchange_rates:
  eur_to_usd: 1.1476
  usd_to_eur: 0.8714
  last_updated: '2026-03-13'
  source: Frankfurter API (ECB data)
_metadata:
  last_pricing_update: '2026-03-15T11:01:09.218117'
  source: Hetzner Cloud API / AWS Pricing API
